Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/precise32"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "2048"
	vb.name = "ICSE-2012-MDSheet-Inference"
  end
  config.vm.provision "shell", inline: <<-SHELL
    
	sudo apt-get update
        cd /home/vagrant/
	sudo apt-get install -y flashplugin-installer

   	#Creating desktop
	sudo apt-get install -y ubuntu-desktop	

	#Adding extensions
	mkdir "/home/vagrant/Desktop"
	mkdir "/home/vagrant/Desktop/Add-on-Extensions"
	wget http://alfa.di.uminho.pt/~jorgemendes/software/mdsheet/experiment001/MDSheetBasic-201305101511.oxt
	wget http://alfa.di.uminho.pt/~jorgemendes/software/mdsheet/experiment001/MDSheet.oxt
	sudo mv /home/vagrant/MDSheetBasic-201305101511.oxt /home/vagrant/Desktop/Add-on-Extensions
	sudo mv /home/vagrant/MDSheet.oxt /home/vagrant/Desktop/Add-on-Extensions
	
	#Adding LICENSE	folder
	mkdir "/home/vagrant/Desktop/LICENSE"
	wget -O "/home/vagrant/Desktop/LICENSE/LICENSE-1.txt" https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-MDSheet/master/build-vm/Ubuntu12.04/vm-contents/LICENSE/LICENSE-1
	wget -O "/home/vagrant/Desktop/LICENSE/LICENSE-2.txt" https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-MDSheet/master/build-vm/Ubuntu12.04/vm-contents/LICENSE/LICENSE-2
	
	#Auto-start application	
	mkdir "/home/vagrant/.config/autostart"
	sudo cp /usr/share/applications/libreoffice-calc.desktop /home/vagrant/.config/autostart/libreoffice-calc.desktop
	
	wget -O "/home/vagrant/Desktop/Installation.txt" https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-MDSheet/master/build-vm/Ubuntu12.04/vm-contents/Installation.txt
	
	wget -O "/home/vagrant/Desktop/README.txt" https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-MDSheet/master/build-vm/Ubuntu12.04/vm-contents/README.txt
	
	wget -O "/home/vagrant/Desktop/Link-to-MDSheet-Demo-by-Author.desktop" https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-MDSheet/master/build-vm/Ubuntu12.04/vm-contents/Link-to-MDSheet-Demo-by-Author.desktop
	
	wget -O "/home/vagrant/Desktop/Link-to-MDSheet-Inference-demo.desktop" https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-MDSheet/master/build-vm/Ubuntu12.04/vm-contents/Link-to-MDSheet-Inference-demo.desktop
	
	sudo chown -R vagrant "/home/vagrant/Desktop"
	sudo chmod -R a+rwx "/home/vagrant/Desktop"	
	
	#Removing screenlock
	mkdir /home/vagrant/scripts
	wget -O "/home/vagrant/scripts/screenlock.sh" https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-MDSheet/master/build-vm/Ubuntu12.04/vm-contents/screenlock.sh
	wget -O "/home/vagrant/.config/autostart/screenlock.desktop" https://raw.githubusercontent.com/SoftwareEngineeringToolDemos/ICSE-2012-MDSheet/master/build-vm/Ubuntu12.04/vm-contents/screenlock.desktop
	sudo chown -R vagrant "/home/vagrant/scripts"
	sudo chmod -R a+rwx "/home/vagrant/scripts"	

        # Remove unused icons from sidebar (making VM as minimal as possible)
     	sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-writer.desktop"
	sudo rm -f "/usr/share/applications/libreoffice-impress.desktop"
	sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"
	
	sudo reboot
   SHELL
end
